export const ADD_EMPLOYEE_INITIAL = 'ADD_EMPLOYEE_INITIAL'
export const ADD_EMPLOYEE_INSERT = 'ADD_EMPLOYEE_INSERT'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL'


export const EMPLOYEE_INITIAL = 'EMPLOYEE_INITIAL'
export const EMPLOYEE_SUCCESS = 'EMPLOYEE_SUCCESS'
export const EMPLOYEE_FAIL = 'EMPLOYEE_FAIL'


export const DELETE_EMPLOYEE_INITIAL = 'DELETE_EMPLOYEE_INITIAL'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'

export const EDIT_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
