export const USER_LOGIN_INITIAL = 'USER_LOGIN_INITIAL'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
